databases:
  - name: Sick Snow
    user: Sick Snow
    plan: free
    region: oregon

services:
  - type: web
    name: Sick Snow
    plan: free
    region: oregon
    branch: main
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Sick Snow
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false